### ISSUE TITLE
factor reordering when adding a plot label to a facet_wrap plot

### ISSUE THREAD

**Issue by JackBuckley** [e61-Institute/theme61#226] opened 2024-10-31 06:09 UTC
**Describe the bug**
When you add a on plot label to a facetted chart the factor ordering is reset. In most cases this doesn't have a noticeable effect, but when you have deliberately ordered a factor in a particular way it is quite annoying.

**Code to reproduce**
Please supply a reproducible example -- the minimum amount of code which recreates the problem you experienced.

Please remove any unnecessary packages or code that are not related to the problem you are experiencing.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aaronw22** [comment] 2024-10-31 06:11
Duplicate of #217

**Closed** 2024-10-31 06:12 UTC
Labels: bug
